[tools]
atlas = "latest"
go = "latest"
golangci-lint = "latest"
gotestsum = "latest"
node = "latest"
protoc = "latest"
protoc-gen-go = "latest"
protoc-gen-go-grpc = "latest"
protoc-gen-validate = "latest"
rust = "latest"

[env]
MISE_NODE_COREPACK = true

[tasks]
build-so-dev-image = { dir = "{{config_root}}", run = 'spark/scripts/build.sh' }
spark-cli = { dir = "{{config_root}}/sdks/js", run = 'yarn install && yarn build && cd examples/spark-cli && yarn build && yarn run cli' }
test-go = { dir = "{{config_root}}/spark", run = 'mise test' }
test-grpc = { dir = "{{config_root}}/spark", run = 'mise test-grpc' }
test-js = { dir = "{{config_root}}/sdks/js", run = 'yarn install && yarn test' }
test-js-integration = { dir = "{{config_root}}/sdks/js", run = 'yarn install && yarn test:integration' }

[settings]
activate_aggressive = true
disable_backends = ["asdf"]
