version: "2"
linters:
  enable:
    - revive
  exclusions:
    generated: lax
    presets:
      - comments
  settings:
    errcheck:
      exclude-functions:
        - (*google.golang.org/grpc.ClientConn).Close
        - (*database/sql.DB).Close
        - (*github.com/lightsparkdev/spark-go/so/ent.Client).Close
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
