[target.aarch64-linux-android]
linker = "aarch64-linux-android33-clang"
rustflags = []

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi33-clang"
rustflags = []

[target.i686-linux-android]
linker = "i686-linux-android33-clang"
rustflags = []

[target.x86_64-linux-android]
linker = "x86_64-linux-android33-clang"
rustflags = []
