[project]
name = ""
version = "0.0.1"
requires-python = "~=3.11"

[dependency-groups]
dev = ["socketsecurity"]

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
