# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build and Lint

on:
  push:
    branches: [ main ]
    paths:
      - 'spark/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'spark/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./spark

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true
        
    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run unit tests
      run: go test $(go list ./... | grep -v -E "so/grpc_test|so/tree")

    - name: Run go fmt
      run: |
        if [ -n "$(gofmt -l .)" ]; then
          echo "The following files are not formatted correctly:"
          gofmt -l .
          exit 1
        fi

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: |
        golint -set_exit_status $(go list ./...)
