name: "Issuer JS SDK Checks"

on:
  push:
    branches:
      - main
    paths:
      - "sdks/issuer-js-sdk/**"
      - ".github/workflows/issuer-js-sdk.yml"
  pull_request:
    paths:
      - "sdks/issuer-js-sdk/**"
      - ".github/workflows/issuer-js-sdk.yml"

jobs:
  checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sdks/issuer-js-sdk

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: sdks/issuer-js-sdk/yarn.lock

      # Allow mutable lockfiles for now in the spark-js-sdk dependency.
      # Soon we will move to npm registries which will resolve this.
      - name: Pack spark-js-sdk
        working-directory: sdks/spark-js-sdk
        run: |
          yarn install --no-immutable
          yarn build
          yarn pack -o ../spark-js-sdk.tgz

      - name: Install dependencies including local package
        run: |
          yarn install --no-immutable
          yarn add ../spark-js-sdk.tgz --mode=update-lockfile
          yarn build
