name: "Spark Hermetic Test Runner"

on:
  workflow_call:
    inputs:
      spark_tag:
        description: "Spark image tag to use for both operator and signer"
        required: false
        default: "latest"
        type: string
      lrc20_tag:
        description: "LRC20 image tag to use"
        required: false
        default: "latest"
        type: string
      test_type:
        description: "Type of test to run. Options: 'go' (default), 'js'"
        required: false
        default: "go"
        type: string
    secrets:
      HELM_PASSWORD:
        required: true

env:
  GO_VERSION: "1.23.2"
  SPARK_TAG: ${{ inputs.spark_tag || 'latest' }}
  LRC20_TAG: ${{ inputs.lrc20_tag || 'latest' }}
  USE_LIGHTSPARK_HELM_REPO: "true"

jobs:
  test:
    runs-on: "ubuntu-22.04-2-arm"
    permissions:
      id-token: write
      contents: write
    concurrency:
      group: hermetic-tests-${{ inputs.test_type }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: "Configure AWS credentials"
        uses: "aws-actions/configure-aws-credentials@v4"
        with:
          role-to-assume: "arn:aws:iam::674966927423:role/github-actions-spark"
          aws-region: "us-west-2"

      - name: "Log into ECR"
        id: ecr-login
        uses: "aws-actions/amazon-ecr-login@v2"

      - name: "Checkout spark-go"
        uses: "actions/checkout@v4"

      - name: "Setup Go"
        uses: "actions/setup-go@v5"
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: "spark/go.sum"

      - name: Install ZMQ dependencies
        run: sudo apt-get update && sudo apt-get install -y libzmq3-dev

      - name: "vmstat"
        run: |
          mkdir logs
          vmstat --wide --unit M --timestamp 5 > logs/vmstat.txt &

      - name: "Install Helm"
        run: |
          HELM_CHECKSUM_SHA256="c86c9b23602d4abbfae39d9634e25ab1d0ea6c4c16c5b154113efe316a402547 */tmp/helm.tar.gz"
          wget -O /tmp/helm.tar.gz https://get.helm.sh/helm-v3.17.1-linux-arm64.tar.gz
          if $(echo "$HELM_CHECKSUM_SHA256" | shasum -c | grep -q FAILED); then
            echo "Mismatched checksum for Helm binary. Cannot install Helm."
            exit 1
          fi
          tar -f /tmp/helm.tar.gz -xzv --strip-components=1 -C /usr/local/bin/

      - name: "Configure Helm repos"
        run: |
          helm repo add --username helm --password "${{ secrets.HELM_PASSWORD }}" lightspark https://helm.sparkinfra.net/
          helm repo add jetstack https://charts.jetstack.io
          helm repo update

      - name: "Start Minikube"
        timeout-minutes: 3
        uses: "medyagh/setup-minikube@master"
        with:
          memory: "4G"
          start-args: >
            --extra-config=apiserver.service-node-port-range=1024-65535
            --extra-config=kubelet.container-log-max-size=50Mi
            --extra-config=kubelet.container-log-max-files=10

      - name: "Configure DNS resolution"
        id: dns
        run: |
          MINIKUBE_IP="$(minikube ip)"
          echo "minikube_ip=$MINIKUBE_IP" >> $GITHUB_OUTPUT

          if ! $(docker network ls | grep -q minikube); then
            echo "Docker network isn't properly configured, ensure the setup-minikube action completed without errors"
            exit 1
          fi

          BRIDGE="$(docker network ls | grep minikube | awk '{print $1}')"
          sudo resolvectl dns "br-$BRIDGE" "$MINIKUBE_IP"
          sudo resolvectl domain "br-$BRIDGE" "~minikube.local"

      - name: "Deploy basic services"
        run: "./scripts/minikube-deploy-basic-services.sh"

      - name: "Deploy Spark services"
        run: "./scripts/minikube-deploy-spark-services.sh"

      - name: "Export Minikube CA"
        run: "./scripts/export-minikube-ca.sh"

      - name: "Setup local signer"
        run: "./scripts/run-local-signer-container.sh"

      - name: "Run DKG"
        working-directory: "./spark"
        env:
          HERMETIC_TEST: "true"
        run: |
          ../scripts/run-development-dkg.sh

      # GO TESTS
      - name: Install gotestsum
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: gotestyourself/gotestsum
          tag: v1.12.0
          cache: enable

      - name: "Run go integration tests"
        if: inputs.test_type == 'go'
        working-directory: "./spark"
        env:
          HERMETIC_TEST: "true"
          GITHUB_ACTIONS: "true"
        run: |
          gotestsum \
          --format testname \
          --rerun-fails=3 \
          --rerun-fails-max-failures=1000 \
          --junitfile ../test_results/grpc-test.xml \
          --jsonfile ../test_results/grpc-test.json \
          --packages=./so/grpc_test/...

      - name: Create test summary
        id: go-create-test-summary
        if: always() && inputs.test_type == 'go'
        uses: test-summary/action@v2
        with:
          paths: "test_results/grpc-test.xml"

      - name: Annotate test failures
        if: |
          always() && inputs.test_type == 'go' &&
          steps.go-create-test-summary.outcome == 'success'
        uses: guyarb/golang-test-annotations@v0.8.0
        with:
          test-results: "test_results/grpc-test.json"

      # JS TESTS
      - name: Enable Corepack
        if: inputs.test_type == 'js'
        working-directory: sdks/js
        run: corepack enable

      - name: Setup Node.js
        if: inputs.test_type == 'js'
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: sdks/js/yarn.lock

      - name: Install dependencies
        if: inputs.test_type == 'js'
        working-directory: sdks/js
        run: yarn install --frozen-lockfile

      - name: Run JS build
        if: inputs.test_type == 'js'
        working-directory: sdks/js
        run: yarn run build

      - name: Run JS tests
        env:
          GITHUB_ACTIONS: "true"
          HERMETIC_TEST: "true"
        if: inputs.test_type == 'js'
        working-directory: sdks/js
        run: yarn run test:integration

      - name: "Gather logs"
        if: always()
        run: |
          set +e
          mkdir -p logs/k8s
          kubectl api-resources --verbs=list -o name | while read TYPE; do
              kubectl describe $TYPE -A >logs/k8s/$TYPE.txt
          done

          pkill vmstat
          source ./scripts/collect-container-logs.sh
          collect_logs "spark" "spark" "operator" "signer" "atlas"
          collect_logs "lrc20" "yuvd" "yuvd" "sea"
          collect_logs "bitcoin" "bitcoind" "bitcoind"
          collect_logs "bitcoin" "electrs" "electrs"
          collect_logs "bitcoin" "mempool" "backend" "frontend"
          kubectl -n bitcoin cp regtest-bitcoind-0:data logs/bitcoind


      - name: "Upload log artifacts"
        if: always()
        uses: "actions/upload-artifact@v4"
        with:
          name: "logs-${{ inputs.test_type }}-${{ github.run_id }}"
          path: logs
          retention-days: 5

      - name: "Cleanup minikube"
        if: always()
        run: "minikube delete"
